#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "technitium-dns"
name = "Technitium DNS"
description.en = "Block ads & malware at DNS level for your entire network! Self host a DNS server for privacy & security"

version = "11.3.0~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-3.0-only"
website = "https://technitium.com/dns/"
admindoc = "https://technitium.com/dns/help.html"
userdoc = "https://technitium.com/dns/help.html"
code = "https://github.com/TechnitiumSoftware/DnsServer"
cpe = "cpe:2.3:a:technitium:dnsserver"
fund = "https://patreon.com/technitium"

[integration]
yunohost = ">= 4.3.0"
architectures = ["arm64", "armhf"]
multi_instance = false
ldap = false
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://download.technitium.com/dns/archive/11.3/DnsServerPortable.tar.gz"
    sha256 = "316290e7ea1c79a856498e7c780ad83a5cc63603f9fb5dee5a22fda42c1689af"
    in_subdir = false

    [resources.sources.dotnet]
    arm64.url = "https://download.visualstudio.microsoft.com/download/pr/9aca092c-f9c0-48d7-a01f-3c1c2eaac903/01b345ddecc7a90d5c99d016fa5180a6/aspnetcore-runtime-7.0.9-linux-arm64.tar.gz"
    arm64.sha256 = "8dc8e5d1373189547aa716c578f9b29afcd7d8d94fd1208650d0809b3af9388b"
    armhf.url = "https://download.visualstudio.microsoft.com/download/pr/3463b963-3438-43db-84eb-e660956c99d6/b8486eb997e3991c5c04800ae8665cc2/aspnetcore-runtime-7.0.9-linux-arm.tar.gz"
    armhf.sha256 = "581bdd9ccef0209cd6ec6b9ff172142eefd9f09332ac98814705af3f91b068ae"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5380
